/**
 * This file was generated by the Jeddict
 */
package co.edu.javeriana.myapp.server.myappserver.model;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * @author oscar
 */
@Entity
public class PiggiMarket {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idSupermercado;

    @Basic
    private String nombre;

    @OneToMany(targetEntity = Usuario.class)
    private List<Usuario> usuarios;

    @OneToMany(targetEntity = Producto.class)
    private List<Producto> productoes;

    @OneToMany(targetEntity = Venta.class)
    private List<Venta> ventas;

    public Long getIdSupermercado() {
        return this.idSupermercado;
    }

    public void setIdSupermercado(Long idSupermercado) {
        this.idSupermercado = idSupermercado;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public List<Usuario> getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(List<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

    public List<Producto> getProductoes() {
        return this.productoes;
    }

    public void setProductoes(List<Producto> productoes) {
        this.productoes = productoes;
    }

    public List<Venta> getVentas() {
        return this.ventas;
    }

    public void setVentas(List<Venta> ventas) {
        this.ventas = ventas;
    }

}