/**
 * This file was generated by the Jeddict
 */
package co.edu.javeriana.myapp.server.myappserver.model;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * @author oscar
 */
@Entity
public class Venta {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idVenta;

    @OneToMany(targetEntity = Lote.class)
    private List<Lote> lotes;

    public Long getIdVenta() {
        return this.idVenta;
    }

    public void setIdVenta(Long idVenta) {
        this.idVenta = idVenta;
    }

    public List<Lote> getLotes() {
        return this.lotes;
    }

    public void setLotes(List<Lote> lotes) {
        this.lotes = lotes;
    }

}